// <auto-generated />
using System;
using LupiraCalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LupiraCalApi.Migrations
{
    [DbContext(typeof(CalDbContext))]
    partial class CalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cal")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LupiraCalApi.Data.AddressBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_address_books");

                    b.HasIndex("OwnerId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_address_books_owner_id_slug");

                    b.ToTable("address_books", "cal");
                });

            modelBuilder.Entity("LupiraCalApi.Data.AddressBookShare", b =>
                {
                    b.Property<Guid>("AddressBookId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_book_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access");

                    b.HasKey("AddressBookId", "UserId")
                        .HasName("pk_address_book_shares");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_address_book_shares_user_id");

                    b.ToTable("address_book_shares", "cal");
                });

            modelBuilder.Entity("LupiraCalApi.Data.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultTimezone")
                        .HasColumnType("text")
                        .HasColumnName("default_timezone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_calendars");

                    b.HasIndex("OwnerId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_calendars_owner_id_slug");

                    b.ToTable("calendars", "cal");
                });

            modelBuilder.Entity("LupiraCalApi.Data.CalendarChange", b =>
                {
                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_type");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("ItemIcalUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_ical_uid");

                    b.HasKey("CalendarId", "Revision")
                        .HasName("pk_calendar_changes");

                    b.ToTable("calendar_changes", "cal");
                });

            modelBuilder.Entity("LupiraCalApi.Data.CalendarShare", b =>
                {
                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access");

                    b.HasKey("CalendarId", "UserId")
                        .HasName("pk_calendar_shares");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_calendar_shares_user_id");

                    b.ToTable("calendar_shares", "cal");
                });

            modelBuilder.Entity("LupiraCalApi.Data.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddressBookId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_book_id");

                    b.Property<string>("Addresses")
                        .HasColumnType("jsonb")
                        .HasColumnName("addresses");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Emails")
                        .HasColumnType("jsonb")
                        .HasColumnName("emails");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text")
                        .HasColumnName("family_name");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("GivenName")
                        .HasColumnType("text")
                        .HasColumnName("given_name");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Organization")
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<string>("Phones")
                        .HasColumnType("jsonb")
                        .HasColumnName("phones");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("SourceVcard")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_vcard");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VcardUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vcard_uid");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("AddressBookId", "VcardUid")
                        .IsUnique()
                        .HasDatabaseName("ix_contacts_address_book_id_vcard_uid");

                    b.ToTable("contacts", "cal");
                });

            modelBuilder.Entity("LupiraCalApi.Data.ContactChange", b =>
                {
                    b.Property<Guid>("AddressBookId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_book_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_type");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("ItemVcardUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_vcard_uid");

                    b.HasKey("AddressBookId", "Revision")
                        .HasName("pk_contact_changes");

                    b.ToTable("contact_changes", "cal");
                });

            modelBuilder.Entity("LupiraCalApi.Data.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attendees")
                        .HasColumnType("jsonb")
                        .HasColumnName("attendees");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("EndTimezone")
                        .HasColumnType("text")
                        .HasColumnName("end_timezone");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("IcalUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ical_uid");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Organizer")
                        .HasColumnType("text")
                        .HasColumnName("organizer");

                    b.Property<DateTimeOffset?>("RecurrenceEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recurrence_ends_at");

                    b.PrimitiveCollection<DateTimeOffset[]>("RecurrenceExcludedDates")
                        .HasColumnType("timestamp with time zone[]")
                        .HasColumnName("recurrence_excluded_dates");

                    b.PrimitiveCollection<DateTimeOffset[]>("RecurrenceExtraDates")
                        .HasColumnType("timestamp with time zone[]")
                        .HasColumnName("recurrence_extra_dates");

                    b.Property<string>("RecurrenceOverrides")
                        .HasColumnType("jsonb")
                        .HasColumnName("recurrence_overrides");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<string>("SourceIcalendar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_icalendar");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("StartTimezone")
                        .HasColumnType("text")
                        .HasColumnName("start_timezone");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("CalendarId", "IcalUid")
                        .IsUnique()
                        .HasDatabaseName("ix_events_calendar_id_ical_uid");

                    b.ToTable("events", "cal");
                });

            modelBuilder.Entity("LupiraCalApi.Data.Relation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_id");

                    b.Property<string>("FromKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_kind");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relation_type");

                    b.Property<string>("ToKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_kind");

                    b.Property<string>("ToRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_ref");

                    b.HasKey("Id")
                        .HasName("pk_relations");

                    b.HasIndex("FromKind", "FromId")
                        .HasDatabaseName("ix_relations_from_kind_from_id");

                    b.ToTable("relations", "cal");
                });

            modelBuilder.Entity("LupiraCalApi.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthentikSub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authentik_sub");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AuthentikSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_authentik_sub");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "cal");
                });

            modelBuilder.Entity("LupiraCalApi.Data.AddressBook", b =>
                {
                    b.HasOne("LupiraCalApi.Data.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_address_books_users_owner_id");
                });

            modelBuilder.Entity("LupiraCalApi.Data.AddressBookShare", b =>
                {
                    b.HasOne("LupiraCalApi.Data.AddressBook", null)
                        .WithMany()
                        .HasForeignKey("AddressBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_address_book_shares_address_books_address_book_id");

                    b.HasOne("LupiraCalApi.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_address_book_shares_users_user_id");
                });

            modelBuilder.Entity("LupiraCalApi.Data.Calendar", b =>
                {
                    b.HasOne("LupiraCalApi.Data.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendars_users_owner_id");
                });

            modelBuilder.Entity("LupiraCalApi.Data.CalendarChange", b =>
                {
                    b.HasOne("LupiraCalApi.Data.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_changes_calendars_calendar_id");
                });

            modelBuilder.Entity("LupiraCalApi.Data.CalendarShare", b =>
                {
                    b.HasOne("LupiraCalApi.Data.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_shares_calendars_calendar_id");

                    b.HasOne("LupiraCalApi.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_shares_users_user_id");
                });

            modelBuilder.Entity("LupiraCalApi.Data.Contact", b =>
                {
                    b.HasOne("LupiraCalApi.Data.AddressBook", null)
                        .WithMany()
                        .HasForeignKey("AddressBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contacts_address_books_address_book_id");
                });

            modelBuilder.Entity("LupiraCalApi.Data.ContactChange", b =>
                {
                    b.HasOne("LupiraCalApi.Data.AddressBook", null)
                        .WithMany()
                        .HasForeignKey("AddressBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_changes_address_books_address_book_id");
                });

            modelBuilder.Entity("LupiraCalApi.Data.Event", b =>
                {
                    b.HasOne("LupiraCalApi.Data.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_calendars_calendar_id");
                });
#pragma warning restore 612, 618
        }
    }
}
